development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://iwcyhizvkgjvvu:e5dfd62ea7e43fdeee753b5f74de91f66b6293de21252ffb8923916492337ea0@ec2-23-23-248-247.compute-1.amazonaws.com:5432/dc05vqctfkf6qa
  channel_prefix: nameofapp_production
